ASP/ExamenASP2/Models/ErrorViewModel.cs
namespace ExamenASP2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP/ExamenASP2/Models/Pelicula.cs
using System.ComponentModel.DataAnnotations;

namespace ExamenASP2.Models
{
    public class Pelicula
    {
        [Required]
        public int Id { get; set; }


        [Required(ErrorMessage = "Este campo es obligatorio")]
        [StringLength(30, ErrorMessage = "Maximo de 30 caracteres.")]
        [RegularExpression(@"^[a-zA-Z0-9][a-zA-Z0-9\s]*$", ErrorMessage = "El texto introducido solo puede contener letras, numeros y/o espacios en blanco.")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "El campo debe ser obligatorio")]
        [Range(1, 500, ErrorMessage = "El campo introducido debe estar comprendido entre 1 y 500")]
        public int Duracion { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Publicacion")]
        public DateTime Fecha_estreno { get; set; }
    }
}

ASP/ExamenASP2/Controllers/EntradasController.cs
using Microsoft.AspNetCore.Mvc;
using static ExamenASP2.Util.PrecioEntrada;

namespace ExamenASP2.Controllers
{
    public class EntradasController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }
        public IActionResult PrecioEntrada()
        {

            return View();
        }
        public IActionResult CalcularPrecioPelicula()
        {
            if (HttpMethods.IsPost(Request.Method))
            {
                /*int pag = int.Parse(Request.Form["paginas"]);
                string color = Request.Form["color"];

                ViewData["precio"] = PrecioComics.CalcularPrecio(pag, color);*/

                int duracion = int.Parse(Request.Form["duracion"]);
                string uhd = Request.Form["uhd"];
                string threed = Request.Form["3d"];

                ViewData["precio"] = Util.PrecioEntrada.CalcularPrecio(duracion, uhd, threed);


            }


            return View("MostrarPrecioEntrada");
        }
    }
}

ASP/ExamenASP2/Controllers/HomeController.cs
using ExamenASP2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExamenASP2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP/ExamenASP2/Controllers/PeliculasController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamenASP2.Data;
using ExamenASP2.Models;

namespace ExamenASP2.Controllers
{
    public class PeliculasController : Controller
    {
        private readonly ExamenASP2Context _context;

        public PeliculasController(ExamenASP2Context context)
        {
            _context = context;
        }

        // GET: Peliculas
        public async Task<IActionResult> Index()
        {
            var peliculas = from p in _context.Pelicula select p;
            if (HttpMethods.IsPost(Request.Method))
            {
                peliculas = peliculas.OrderByDescending(p => p.Titulo);
            }

            return View(await peliculas.ToListAsync());
        }

        // GET: Peliculas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Pelicula
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        // GET: Peliculas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Duracion,Fecha_estreno")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pelicula);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Pelicula.FindAsync(id);
            if (pelicula == null)
            {
                return NotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Duracion,Fecha_estreno")] Pelicula pelicula)
        {
            if (id != pelicula.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pelicula);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeliculaExists(pelicula.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Pelicula
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pelicula = await _context.Pelicula.FindAsync(id);
            _context.Pelicula.Remove(pelicula);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeliculaExists(int id)
        {
            return _context.Pelicula.Any(e => e.Id == id);
        }
    }
}

ASP/ExamenASP2/Views/Peliculas/Create.cshtml
@model ExamenASP2.Models.Pelicula

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pelicula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duracion" class="control-label"></label>
                <input asp-for="Duracion" class="form-control" />
                <span asp-validation-for="Duracion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_estreno" class="control-label"></label>
                <input asp-for="Fecha_estreno" class="form-control" />
                <span asp-validation-for="Fecha_estreno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP/ExamenASP2/Views/Peliculas/Delete.cshtml
@model ExamenASP2.Models.Pelicula

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duracion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha_estreno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha_estreno)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASP/ExamenASP2/Views/Peliculas/Details.cshtml
@model ExamenASP2.Models.Pelicula

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duracion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha_estreno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha_estreno)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASP/ExamenASP2/Views/Peliculas/Edit.cshtml
@model ExamenASP2.Models.Pelicula

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pelicula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duracion" class="control-label"></label>
                <input asp-for="Duracion" class="form-control" />
                <span asp-validation-for="Duracion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_estreno" class="control-label"></label>
                <input asp-for="Fecha_estreno" class="form-control" />
                <span asp-validation-for="Fecha_estreno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP/ExamenASP2/Views/Peliculas/Index.cshtml
@using ExamenASP2.Util
@model IEnumerable<ExamenASP2.Models.Pelicula>


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Peliculas" asp-action="Index">
    
     Ordenar por orden alfabetico inverso
     <input type="submit" value="Filter" />

</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duracion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_estreno)
            </th>
            <th>Dias transcurridos</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duracion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_estreno)
            </td>
            <td>
                @CantidadDias.CalculaDias(item.Fecha_estreno)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ASP/ExamenASP2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenASP2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamenASP2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamenASP2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExamenASP2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>