ASP/SimulacroASP/Models/ErrorViewModel.cs
namespace SimulacroASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP/SimulacroASP/Models/Manga.cs
using System.ComponentModel.DataAnnotations;

namespace SimulacroASP.Models
{
    public class Manga
    {
        [Required(ErrorMessage = "El campo debe ser obligatorio")]
        public int Id { get; set; }
        
        [Required (ErrorMessage="El campo debe ser obligatorio")]
        [StringLength (30, ErrorMessage = "Maximo 30 caracteres")]
        [RegularExpression(@"^[a-zA-Z0-9\s]+$", ErrorMessage = "El campo solo admite letras, numeros y espacios en blanco.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "El campo debe ser obligatorio")]
        [Range(1,1000, ErrorMessage = "El campo introducido debe estar comprendido entre 1 y 1000")]
        public int Pages { get; set; }

        [Required(ErrorMessage = "El campo debe ser obligatorio")]
        [StringLength(20, ErrorMessage = "Maximo 20 caracteres")]
        [RegularExpression(@"^[a-zA-Z0-9\s]+$", ErrorMessage = "El campo solo admite letras, numeros y espacios en blanco.")]
        public string Color { get; set; }
    }
}

ASP/SimulacroASP/Controllers/ComicsController.cs
using Microsoft.AspNetCore.Mvc;
using SimulacroASP.util;

namespace SimulacroASP.Controllers
{
    public class ComicsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PrecioComic()
        {
 
            return View(); 
        }
        public IActionResult mostrarFuncion()
        {
            if (HttpMethods.IsPost(Request.Method))
            {
                int pag = int.Parse(Request.Form["paginas"]);
                string color = Request.Form["color"];

                ViewData["precio"] = PrecioComics.CalcularPrecio(pag, color);

            }

            
            return View("MostrarPrecioComic");
        }
    }
}

ASP/SimulacroASP/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SimulacroASP.Models;
using System.Diagnostics;

namespace SimulacroASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP/SimulacroASP/Controllers/MangasController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimulacroASP.Data;
using SimulacroASP.Models;

namespace SimulacroASP.Controllers
{
    public class MangasController : Controller
    {
        private readonly SimulacroASPContext _context;

        public MangasController(SimulacroASPContext context)
        {
            _context = context;
        }

        // GET: Mangas
        public async Task<IActionResult> Index(string searchString)
        {
            var mangas = from m in _context.Manga select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                mangas = mangas.Where(m => m.Name!.Contains(searchString));
            }

            return View(await mangas.ToListAsync());
        }

        // GET: Mangas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manga == null)
            {
                return NotFound();
            }

            return View(manga);
        }

        // GET: Mangas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Mangas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Pages,Color")] Manga manga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manga);
        }

        // GET: Mangas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga.FindAsync(id);
            if (manga == null)
            {
                return NotFound();
            }
            return View(manga);
        }

        // POST: Mangas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Pages,Color")] Manga manga)
        {
            if (id != manga.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MangaExists(manga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manga);
        }

        // GET: Mangas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manga == null)
            {
                return NotFound();
            }

            return View(manga);
        }

        // POST: Mangas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manga = await _context.Manga.FindAsync(id);
            _context.Manga.Remove(manga);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MangaExists(int id)
        {
            return _context.Manga.Any(e => e.Id == id);
        }
    }
}

ASP/SimulacroASP/Views/Mangas/Create.cshtml
@model SimulacroASP.Models.Manga

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Manga</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pages" class="control-label"></label>
                <input asp-for="Pages" class="form-control" />
                <span asp-validation-for="Pages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <select asp-for="Color" class="form-control">
                    <option value = "BlancoNegro">Blanco y Negro</option>
                    <option value = "color">Color</option>
                </select>
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP/SimulacroASP/Views/Mangas/Delete.cshtml
@model SimulacroASP.Models.Manga

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Manga</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASP/SimulacroASP/Views/Mangas/Details.cshtml
@model SimulacroASP.Models.Manga

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Manga</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASP/SimulacroASP/Views/Mangas/Edit.cshtml
@model SimulacroASP.Models.Manga

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Manga</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pages" class="control-label"></label>
                <input asp-for="Pages" class="form-control" />
                <span asp-validation-for="Pages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP/SimulacroASP/Views/Mangas/Index.cshtml
@using SimulacroASP.util
@model IEnumerable<SimulacroASP.Models.Manga>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Mangas" asp-action="Index">
    
     Title: <input type="text" name="SearchString" />
     <input type="submit" value="Filter" />

</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pages)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>Precio</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pages)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @PrecioComics.CalcularPrecio(item.Pages, item.Color)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>